DROP TABLE IF EXISTS branch;
DROP TABLE IF EXISTS node;
DROP TABLE IF EXISTS pickup_point;

CREATE TABLE branch (
  id INT AUTO_INCREMENT  PRIMARY KEY,
  address VARCHAR(250) NOT NULL,
  date_attention DATE NOT NULL,
  latitude VARCHAR(250) NOT NULL,
  longitude VARCHAR(250) NOT NULL
);

CREATE TABLE pickup_point(
	id INT AUTO_INCREMENT  PRIMARY KEY,
	capacity INT NOT NULL,
	latitude VARCHAR(250) NOT NULL,
	longitude VARCHAR(250) NOT NULL
);

CREATE TABLE node (
  id INT AUTO_INCREMENT PRIMARY KEY,
  branch_id INT DEFAULT NULL,
  pickup_id INT DEFAULT NULL
);